language: c
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - binutils-mingw-w64-i686
      - binutils-mingw-w64-x86-64
      - gcc-mingw-w64
      - gcc-mingw-w64-base
      - gcc-mingw-w64-i686
      - gcc-mingw-w64-x86-64
      - gcc-multilib
      - tcl8.6-dev
      - libgdbm-dev
      - liblmdb-dev
  homebrew:
    packages:
      - tcl-tk
      - gdbm
      - lmdb
jobs:
  include:
# "make dist" only
    - name: "Linux: make dist"
      os: linux
      dist: focal
      compiler: gcc
      script:
        - make dist
before_install:
  - |-
      case $TRAVIS_OS_NAME in
        windows)
          choco install -y magicsplat-tcl-tk
          ;;
      esac
install:
  - mkdir "$HOME/install dir"
  - mkdir tclconfig
  - touch tclconfig/README.txt
  - touch tclconfig/tcl.m4
  - curl https://core.tcl-lang.org/tclconfig/raw/install-sh?name=f46cea65709582bed664d69a40095db0490968df69c355e30cd8905f0b60a153 >tclconfig/install-sh
  - ./configure "--prefix=$HOME/install dir" || (cat config.log && exit 1)
script:
  - make
  - make test >out.txt
  - cat out.txt
  - grep -q "Failed	0" out.txt
cache:
  directories:
  - $HOME/AppData/Local/Temp/chocolatey
  - $HOME/AppData/Local/Apps/Tcl86
